config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :books
  root to: 'homes#top'
  get 'home/about' => 'homes#about',as: :about
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title,presence: true
  validates :body,presence: true,length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books,dependent: :destroy
  has_one_attached :profile_image

  # def get_profile_image(width,height)
  #   if profile_image.attached?
  #     profile_image
  #   else
  #     "no_image.jpeg"
  #   end
  # end

  validates :name,uniqueness: true,length: {minimum: 2 , maximum: 20}
  validates :introduction,length: {maximum: 50}

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path=Rails.root.join("app/assets/images/no_image.jpeg")
      profile_image.attach(io: File.open(file_path),filename: "default-image.jpg",content_type: "image/jpeg")
    end
      profile_image.variant(resize_to_limit: [width,height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters,if: :devise_controller?
  before_action :authenticate_user!,except: [:top,:about,:sign_up,:sign_in]

  def after_sign_in_path_for(resourse)
    user_path(current_user)
  end

  def after_sign_out_path_for(resourse)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    # devise_parameter_sanitizer.permit(:sign_in, key: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books=Book.all
    @user=User.find(current_user.id)
    @book=Book.new()
  end

  def create
    @books=Book.all
    @user=User.find(current_user.id)
    @book=Book.new(book_params)
    @book.user_id=current_user.id
    if @book.save
      flash[:notice]="You have submitted successfully"
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def show
    @book=Book.find(params[:id])
  end

  def edit
    @book=Book.find(params[:id])
    redirect_to books_path unless @book.user_id==current_user.id
  end

  def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice]="You have edited successfully"
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book=Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.all
  end

  def show
    @user=User.find(params[:id])
  end

  def edit
    @user=User.find(params[:id])
    unless @user==current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have edited successfully"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:profile_image,:introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-lg-6 mx-auto">
      <h2>Editing Book</h2>
       <div class="mt-3">
        <% if @book.errors.any? %>
          <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
          <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        <% end %>
      </div>
      <%= form_with model: @book,url: book_path(@book.id),method: :patch do |f| %>
        <div class="form-group mt-2">
          <%= f.label :title %><br>
          <%= f.text_field :title,class: "form-control" %>
        </div>

        <div class="form-group mt-2">
          <%= f.label :body,"Opinion" %><br>
          <%= f.text_area :body,class: "form-control" %>
        </div>

        <div class="action">
          <%= f.submit "Update Book" ,class: "btn btn-success" %>
        </div>
      <% end %>

      <p class="mt-3">
        <%= link_to "Show" ,book_path(@book.id) %>  |  <%= link_to "Back" ,books_path %>
      </p>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="mt-3">
    <% if @book.errors.any? %>
      <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    <% end %>
  </div>
  <div class="row mt-5">
    <div class="col-md-3">
      <%= render partial: 'users/user.html.erb', locals: {user: @user} %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user_id) do %>
                <%= image_tag book.user.get_profile_image(100,100) %>
              <% end %>
            </td>
            <td class="align-middle">
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td class="align-middle"><%= book.body %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <hr class="mt-0">
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-md-3">
      <%= render partial: 'users/user.html.erb', locals: {user: @book.user} %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <% if @book.user_id==current_user.id %>
              <th></th>
              <th></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user_id) do %>
                <%= image_tag @book.user.get_profile_image(100,100) %><br>
                <%= @book.user.name %>
              <% end %>
            </td>
            <td class="align-middle">
              <%= link_to book_path(@book.id) do %>
                <%= @book.title %>
              <% end %>
            </td>
            <td class="align-middle"><%= @book.body %></td>
            <% if @book.user_id==current_user.id %>
              <td class="align-middle">
                <%= link_to edit_book_path(@book.id) do %>
                  <span class="btn btn-success">Edit</span>
                <% end %>
              </td>
              <td class="align-middle">
                <%= link_to book_path(@book.id),method: :delete ,"data-confirm" => "本当に削除しますか？" do %>
                  <span class="btn btn-danger align-middle">Destroy</span>
                <% end %>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <hr class="mt-0">
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-lg-6 col-sm-4 mx-auto">
      <h1 class="mb-3 text-center">welcome to<i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-lg-6 col-sm-4 mx-auto">
      <h1 class="mb-3">welcome to<i class="fas fa-book"></i><strong>Bookers</strong>!!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p>
        you can share and exchange your opinions , inpressions , and emotions<br>
        about various books!
      </p>
      <%= link_to new_user_session_path do %>
        <p class="btn btn-info btn-block">Log in</p>
      <% end %>
      <%= link_to new_user_registration_path do %>
        <p class="btn btn-success btn-block">Sign up</p>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReBookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/4ac72d4f08.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
        <div class=container>
          <a href="/" class="navbar-brand">
            Bookers
          </a>
          <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav"
          aria-label="Toggle navigation" aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in?  %>
              <%= link_to user_path(current_user.id) do %>
                <li class="p-2 text-light">
                  <span><i class="fas fa-home"></i> Home</span>
                </li>
              <% end %>
              <%= link_to users_path do %>
                <li class="p-2 text-light">
                  <span><i class="fas fa-users"></i> Users</span>
                </li>
              <% end %>
              <%= link_to books_path do %>
                <li class="p-2 text-light">
                  <span><i class="fas fa-book-open"></i> Books</span>
                </li>
              <% end %>
              <%= link_to destroy_user_session_path,method: :delete do %>
                <li class="p-2 text-light">
                  <span><i class="fas fa-sign-out-alt"></i> Log out</span>
                </li>
              <% end %>
            <% else %>
              <%= link_to root_path do %>
                <li class="p-2 text-light">
                  <span><i class="fas fa-home"></i> Home</span>
                </li>
              <% end %>
              <%= link_to about_path do %>
                <li class="p-2 text-light">
                  <span><i class="fas fa-link"></i> About</span>
                </li>
              <% end %>
              <%= link_to new_user_registration_path do %>
                <li class="p-2 text-light">
                  <i class="fas fa-user-plus"></i> Sign up</span>
                </li>
              <% end %>
              <%= link_to new_user_session_path do %>
                <li class="p-2 text-light">
                  <span><i class="fas fa-sign-in-alt"></i> Log in</span>
                </li>
              <% end %>
            <% end %>
            </ul>
          </div>
      </nav>
    </header>

    <div>
      <% flash.each do |key,value| %>
        <p><%= value %></p>
      <% end %>
    </div>

    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight FurutaShinya</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_user.html.erb
<h2>User info</h2>
<div>
  <%= image_tag user.get_profile_image(100,100) %>
</div>
<table class="table">
  <tbody>
    <tr>
      <td>name</td>
      <td><%= user.name %></td>
    </tr>
    <tr>
      <td>introduction</td>
      <td><%= user.introduction %></td>
    </tr>
  </tbody>
</table>

<div class="btn btn-outline-secondary btn-block mt-5">
  <%= link_to edit_user_path(user.id) do %>
    <i class="fas fa-user-cog text-secondary"></i>
  <% end %>
</div>

<h2 class="mt-5">New book</h2>
<%= form_with model: Book.new, url: books_path,method: :post do |f|%>

  <div class="form-group mt-3">
    <%= f.label :title %><br>
    <%= f.text_field :title ,class: "form-control" %>
  </div>

  <div class="form-group mt-3">
    <%= f.label :body %><br>
    <%= f.text_area :body ,class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Create Book" ,class: "btn btn-success" %>
  </div>

<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-lg-6 mx-auto">
      <h2>User info</h2>
        <div class="mt-3">
          <% if @user.errors.any? %>
            <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
            <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          <% end %>
        </div>
        
        <%= form_with model: @user,url: user_path(@user.id),method: :patch do |f| %>
        <div class="form-group mt-2">
          <%= f.label :name %><br>
          <%= f.text_field :name,class: "form-control" %>
        </div>

        <div class="form-group mt-2">
          <%= f.label :profile_image ,"Image" %><br>
          <%= f.file_field :profile_image %>
        </div>

        <div class="form-group mt-2">
          <%= f.label :introduction %><br>
          <%= f.text_area :introduction,class: "form-control" %>
        </div>

        <div class="action">
          <%= f.submit "Update User" ,class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-md-3">
      <%= render partial: 'users/user.html.erb', locals: {user: current_user} %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td>
              <%= image_tag user.get_profile_image(100,100) %>
            </td>
            <td class="align-middle">
                <%= user.name %>
            </td>
            <td class="align-middle">
              <%= link_to "Show" ,user_path(user.id) %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <hr class="mt-0">
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-md-3">
      <%= render partial: 'users/user.html.erb', locals: {user: @user} %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
        <% @user.books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user_id) do %>
                <%= image_tag book.user.get_profile_image(100,100) %>
              <% end %>
            </td>
            <td class="align-middle">
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td class="align-middle"><%= book.body %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <hr class="mt-0">
    </div>
  </div>
</div>